### ISSUE TITLE
Exception: CUDAExecutionProvider is not avaiable in onnxruntime

### ISSUE THREAD

**Issue by fortminors** [iperov/DeepFaceLive#13]
Hello!

I am trying to run the demo program, following [this](https://github.com/iperov/DeepFaceLive/blob/master/doc/setup_tutorial_windows/index.md) tutorial, however at the point when I choose the device for the face detector, it goes red and the terminal has this output:

```
FaceDetector error: CUDAExecutionProvider is not avaiable in onnxruntime Traceback (most recent call last):
  File "D:\Desktop\DeepFaceLive-master\xlib\mp\csw\CSWBase.py", line 472, in _start_proc
    self.on_start(*worker_start_args, **worker_start_kwargs)
  File "D:\Desktop\DeepFaceLive-master\apps\DeepFaceLive\backend\FaceDetector.py", line 81, in on_start
    cs.detector_type.select(state.detector_type)
  File "D:\Desktop\DeepFaceLive-master\xlib\mp\csw\DynamicSingleSwitch.py", line 99, in select
    result = self._set_selected_idx(idx_or_choice)
  File "D:\Desktop\DeepFaceLive-master\xlib\mp\csw\DynamicSingleSwitch.py", line 33, in _set_selected_idx
    self._on_selected_evl.call(selected_idx, self.get_selected_choice() )
  File "D:\Desktop\DeepFaceLive-master\xlib\python\EventListener.py", line 24, in call
    func(*args, **kwargs)
  File "D:\Desktop\DeepFaceLive-master\apps\DeepFaceLive\backend\FaceDetector.py", line 99, in on_cs_detector_type
    cs.device.select(state.YoloV5_state.device)
  File "D:\Desktop\DeepFaceLive-master\xlib\mp\csw\DynamicSingleSwitch.py", line 99, in select
    result = self._set_selected_idx(idx_or_choice)
  File "D:\Desktop\DeepFaceLive-master\xlib\mp\csw\DynamicSingleSwitch.py", line 33, in _set_selected_idx
    self._on_selected_evl.call(selected_idx, self.get_selected_choice() )
  File "D:\Desktop\DeepFaceLive-master\xlib\python\EventListener.py", line 24, in call
    func(*args, **kwargs)
  File "D:\Desktop\DeepFaceLive-master\apps\DeepFaceLive\backend\FaceDetector.py", line 144, in on_cs_devices
    self.YoloV5Face = onnx_models.YoloV5Face(device)
  File "D:\Desktop\DeepFaceLive-master\modelhub\onnx\YoloV5Face\YoloV5Face.py", line 34, in __init__
    self._sess = sess = InferenceSession_with_device(str(path), device_info)
  File "D:\Desktop\DeepFaceLive-master\xlib\onnxruntime\InferenceSession.py", line 23, in InferenceSession_with_device
    raise Exception('CUDAExecutionProvider is not avaiable in onnxruntime')
Exception: CUDAExecutionProvider is not avaiable in onnxruntime
```

I have CUDA 11.4 installed with the cudnn support. My graphics card is GTX 1080 Ti.

Looking forward to hearing from you! Thanks.

**Comment by iperov** [comment]
According tutorial, you don't need to install cuda or cudnn.

**Comment by iperov** [comment]
use prebuild windows binary.

**Comment by iperov** [comment]
DeepFaceLive-master\ - no such paths in windows binary.
