### ISSUE TITLE
Unable to load kernel32 library

### ISSUE THREAD

**Issue by JustinH71** [iperov/DeepFaceLive#28]
Running DeepFaceLive.
Traceback (most recent call last):
  File "_internal\DeepFaceLive\main.py", line 95, in <module>
    main()
  File "_internal\DeepFaceLive\main.py", line 88, in main
    args.func(args)
  File "_internal\DeepFaceLive\main.py", line 30, in run_DeepFaceLive
    from apps.DeepFaceLive.DeepFaceLiveApp import DeepFaceLiveApp
  File "D:\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\apps\DeepFaceLive\DeepFaceLiveApp.py", line 14, in <module>
    from . import backend
  File "D:\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\apps\DeepFaceLive\backend\__init__.py", line 1, in <module>
    from .BackendBase import (BackendConnection, BackendConnectionData, BackendDB,
  File "D:\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\apps\DeepFaceLive\backend\BackendBase.py", line 7, in <module>
    from xlib import time as lib_time
  File "D:\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\xlib\time\__init__.py", line 1, in <module>
    from .time_ import timeit, measure, FPSCounter, AverageMeasurer
  File "D:\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\xlib\time\time_.py", line 11, in <module>
    if not kernel32.QueryPerformanceFrequency(_perf_freq):
  File "D:\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\xlib\api\win32\wintypes\wintypes.py", line 32, in wrapper
    raise RuntimeError(f'Unable to load {dll_name} library.')
RuntimeError: Unable to load kernel32 library.
Press any key to continue . . .

I've tried both versions. I have an rtx 2070 with 8gig of vram.  All other programs work just fine. Deepfacelab works great to. This is the only program that won't run. I've tried everything. Even tried replacing the kernel32.dll with another windows 10 kernel.dll.

**Comment by iperov** [comment]
another windows 10?
program works fine with latest windows 10.

**Comment by JustinH71** [comment]
I am running the latest windows 10

**Comment by JustinH71** [comment]
I just upgraded to windows 11 and now it works great. I new it was on my end.

**Comment by AndrewHayes1724** [comment]
This is happening to me in 2023 randomly. I am still using Windows 10 not 11.
