### ISSUE TITLE
CUDA wont work on CUDA version with GTX 780

### ISSUE THREAD

**Issue by 2blackbar** [iperov/DeepFaceLive#35]
Heres the error , newest python instaled, gtx drivers 472.12
`Running DeepFaceLive.
FaceDetector error: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Sigmoid node. Name:'Sigmoid_1' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device Traceback (most recent call last):
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\xlib\mp\csw\CSWBase.py", line 484, in _start_proc
    self.on_tick()
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\apps\DeepFaceLive\backend\FaceDetector.py", line 234, in on_tick
    rects = self.YoloV5Face.extract (frame_image, threshold=detector_state.threshold, fixed_window=detector_state.fixed_window_size)[0]
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\modelhub\onnx\YoloV5Face\YoloV5Face.py", line 74, in extract
    preds = self._get_preds(ip.get_image('NCHW'))
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\modelhub\onnx\YoloV5Face\YoloV5Face.py", line 106, in _get_preds
    preds = self._sess.run(None, {self._input_name: img})
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Sigmoid node. Name:'Sigmoid_1' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

FaceDetector error: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Sigmoid node. Name:'Sigmoid_1' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device Traceback (most recent call last):
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\xlib\mp\csw\CSWBase.py", line 484, in _start_proc
    self.on_tick()
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\apps\DeepFaceLive\backend\FaceDetector.py", line 234, in on_tick
    rects = self.YoloV5Face.extract (frame_image, threshold=detector_state.threshold, fixed_window=detector_state.fixed_window_size)[0]
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\modelhub\onnx\YoloV5Face\YoloV5Face.py", line 74, in extract
    preds = self._get_preds(ip.get_image('NCHW'))
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\modelhub\onnx\YoloV5Face\YoloV5Face.py", line 106, in _get_preds
    preds = self._sess.run(None, {self._input_name: img})
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Sigmoid node. Name:'Sigmoid_1' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

FaceMarker error: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Transpose node. Name:'conv2d_1__50' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device Traceback (most recent call last):
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\xlib\mp\csw\CSWBase.py", line 484, in _start_proc
    self.on_tick()
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\apps\DeepFaceLive\backend\FaceMarker.py", line 173, in on_tick
    lmrks = self.google_facemesh.extract(face_image)[0]
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\modelhub\onnx\FaceMesh\FaceMesh.py", line 57, in extract
    lmrks = self._sess.run(None, {self._input_name: feed_img})[0]
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Transpose node. Name:'conv2d_1__50' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

FaceSwapper error: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Transpose node. Name:'transpose_21' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device Traceback (most recent call last):
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\xlib\mp\csw\CSWBase.py", line 484, in _start_proc
    self.on_tick()
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\apps\DeepFaceLive\backend\FaceSwapper.py", line 280, in on_tick
    celeb_face, celeb_face_mask_img, face_align_mask_img = dfm_model.convert(face_align_image, morph_factor=model_state.morph_factor)
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\modelhub\DFLive\DFMModel.py", line 114, in convert
    out_face_mask, out_celeb, out_celeb_mask = self._sess.run(None, {'in_face:0': img})
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Transpose node. Name:'transpose_21' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

FaceMarker error: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Transpose node. Name:'conv2d_1__50' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device Traceback (most recent call last):
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\xlib\mp\csw\CSWBase.py", line 484, in _start_proc
    self.on_tick()
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\apps\DeepFaceLive\backend\FaceMarker.py", line 173, in on_tick
    lmrks = self.google_facemesh.extract(face_image)[0]
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\modelhub\onnx\FaceMesh\FaceMesh.py", line 57, in extract
    lmrks = self._sess.run(None, {self._input_name: feed_img})[0]
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Transpose node. Name:'conv2d_1__50' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

FaceDetector error: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Sigmoid node. Name:'Sigmoid_1' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device Traceback (most recent call last):
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\xlib\mp\csw\CSWBase.py", line 484, in _start_proc
    self.on_tick()
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\apps\DeepFaceLive\backend\FaceDetector.py", line 234, in on_tick
    rects = self.YoloV5Face.extract (frame_image, threshold=detector_state.threshold, fixed_window=detector_state.fixed_window_size)[0]
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\modelhub\onnx\YoloV5Face\YoloV5Face.py", line 74, in extract
    preds = self._get_preds(ip.get_image('NCHW'))
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\DeepFaceLive\modelhub\onnx\YoloV5Face\YoloV5Face.py", line 106, in _get_preds
    preds = self._sess.run(None, {self._input_name: img})
  File "J:\SOFT\DeepFaceLive_NVIDIA\_internal\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Sigmoid node. Name:'Sigmoid_1' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device

Press any key to continue . . .`

**Comment by iperov** [comment]
perhaps GTX 780 is now old . Use directx version.
Also you don't need to install python.
