### ISSUE TITLE
QPainter::begin: Paint device returned engine == 0, type: 2

### ISSUE THREAD

**Issue by nikell28** [iperov/DeepFaceLive#83]
```
Running DeepFaceLive.
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setCompositionMode: Painter not active
QPainter::end: Painter not active, aborted
Traceback (most recent call last):
  File "main.py", line 254, in <module>
    main()
  File "main.py", line 247, in main
    args.func(args)
  File "main.py", line 187, in run_DeepFaceLive
    deep_face_live_app_inst = DeepFaceLiveApp(userdata_path=userdata_path)
  File "/home/administrator/Projects/deepfacelive/apps/DeepFaceLive/DeepFaceLiveApp.py", line 238, in __init__
    self.initialize()
  File "/home/administrator/Projects/deepfacelive/apps/DeepFaceLive/DeepFaceLiveApp.py", line 254, in initialize
    self.dfl_wnd = self._dfl_wnd = QDFLAppWindow(userdata_path=self.userdata_path, settings_dirpath=self.settings_dirpath)
  File "/home/administrator/Projects/deepfacelive/apps/DeepFaceLive/DeepFaceLiveApp.py", line 197, in __init__
    q_live_swap = self.q_live_swap = QLiveSwap(userdata_path=self._userdata_path, settings_dirpath=self._settings_dirpath)
  File "/home/administrator/Projects/deepfacelive/apps/DeepFaceLive/DeepFaceLiveApp.py", line 69, in __init__
    self.q_file_source    = QFileSource(self.file_source)
  File "/home/administrator/Projects/deepfacelive/apps/DeepFaceLive/ui/QFileSource.py", line 22, in __init__
    self.q_input_paths = QPathEditCSWPaths(cs.input_paths)
  File "/home/administrator/Projects/deepfacelive/apps/DeepFaceLive/ui/widgets/QPathEditCSWPaths.py", line 30, in __init__
    btn_open = self._btn_open = qtx.QXPushButton(image=QXImageDB.folder_open_outline(color='light gray'),
  File "/home/administrator/Projects/deepfacelive/xlib/qt/widgets/QXPushButton.py", line 28, in __init__
    self._set_image(image)
  File "/home/administrator/Projects/deepfacelive/xlib/qt/widgets/QXPushButton.py", line 88, in _set_image
    self._update_icon_size()
  File "/home/administrator/Projects/deepfacelive/xlib/qt/widgets/QXPushButton.py", line 71, in _update_icon_size
    pixmap_aspect = size.width() / size.height()
ZeroDivisionError: division by zero
```

Ubuntu 22.04
Help me please!

**Comment by Kundanagrawalofficial** [comment]
This error message is indicating that there is a problem with the QXPushButton widget in the QFileSource class in the "main.py" file. Specifically, it is trying to divide the width of the "size" variable by its height, which results in a division by zero error.

The reason for this error could be that the "size" variable is not being initialized with a valid value. This could happen if the image being passed to the QXPushButton widget is not being loaded properly, or if the image file is missing or corrupted.

It could also be that the image file is not in the correct location and the path is not correct.

One possible solution would be to check the path of the image file and ensure that it is accessible by the program. Also, make sure the image file is not corrupt and it's the correct format.

Another solution would be to handle the exception by adding a try-except block around the division operation, and provide a default value or alternative behavior in the except block.

You may also want to check for other missing or corrupted image files used in the code.

**Comment by iperov** [comment]
closed but feel free to update
